### ISSUE TITLE
"ip_pool" - [SparkPostError]: Unprocessable Entity

### ISSUE THREAD

**Issue by dommermuth** [SparkPost/node-sparkpost#248]
Hello,  I'm trying to add ip_pool to the options, but the transmission is rejected with:

`Error [SparkPostError]: Unprocessable Entity
    at createSparkPostError (C:\node_modules\sparkpost\lib\sparkpost.js:38:15)
    at Request._callback (C:\node_modules\sparkpost\lib\sparkpost.js:128:15)
    at Request.self.callback (C:\node_modules\request\request.js:185:22)
    at Request.emit (events.js:321:20)
    at Request.<anonymous> (C:\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:321:20)
    at IncomingMessage.<anonymous> (C:\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:427:28)
    at IncomingMessage.emit (events.js:333:22)
    at endReadableNT (_stream_readable.js:1204:12) {
  name: 'SparkPostError',
  errors: [
    {
      message: 'invalid data format/type',
      description: `IP Pool '"xxx.xxx.xx.xx"' does not exist`,
      code: '1300'
    }
  ],`

I'm able to use it with PHP and requesting with Curl, but not here.  Is IP Pool not needed?

Kurt

**Comment by dommermuth** [comment]
Closing this.  I was passing the actual ip rather than the name of the pool.
